-- Mark whether a payment was auto-generated by the cron job
ALTER TABLE public.subscription_payment_logs
  ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN NOT NULL DEFAULT FALSE;

-- ─── Auto-pay function ───────────────────────────────────────────────────────
-- Registers a payment for every active auto-renewal subscription whose
-- next_billing_date has arrived and hasn't been paid yet.
--
-- Billing date advancement anchors to the day-of-month of created_at so the
-- date never drifts (e.g. a subscription created on the 31st always bills on
-- the last day of each month, not the 28th after hitting February).
--
-- Formula for monthly (same pattern for quarterly/semiannual/annual):
--   LEAST(
--     first_of_target_month + (anchor_day - 1),   -- ideal date
--     last_day_of_target_month                     -- clamp for short months
--   )
--
-- Returns the number of payments created.
CREATE OR REPLACE FUNCTION public.auto_register_subscription_payments()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_count integer := 0;
BEGIN
  -- 1. Insert payment log entries for all due subscriptions
  INSERT INTO public.subscription_payment_logs
    (subscription_id, amount, payment_date, payment_method, auto_generated, recorded_by)
  SELECT
    s.id                                         AS subscription_id,
    s.amount * COALESCE(s.license_count, 1)      AS total_amount,
    s.next_billing_date                          AS billing_date,
    s.payment_method,
    TRUE,
    s.created_by
  FROM public.subscriptions s
  WHERE s.auto_renewal   = TRUE
    AND s.status         = 'active'
    AND s.billing_cycle != 'pay_as_you_go'
    AND s.next_billing_date IS NOT NULL
    AND s.next_billing_date <= CURRENT_DATE
    -- avoid double-payment: only if we haven't paid on or after this billing date
    AND (s.last_paid_at IS NULL
         OR s.last_paid_at::date < s.next_billing_date);

  GET DIAGNOSTICS v_count = ROW_COUNT;

  -- 2. Advance next_billing_date anchored to the day of month from created_at.
  --    For each cycle, we jump to the start of the target month and add
  --    (anchor_day - 1) days, then clamp to the last day of that month.
  UPDATE public.subscriptions s
  SET
    last_paid_at      = s.next_billing_date,
    next_billing_date = CASE s.billing_cycle
      WHEN 'monthly' THEN
        LEAST(
          DATE_TRUNC('month', s.next_billing_date + INTERVAL '1 month')::date
            + (EXTRACT(DAY FROM s.created_at)::int - 1),
          (DATE_TRUNC('month', s.next_billing_date + INTERVAL '2 months') - INTERVAL '1 day')::date
        )
      WHEN 'quarterly' THEN
        LEAST(
          DATE_TRUNC('month', s.next_billing_date + INTERVAL '3 months')::date
            + (EXTRACT(DAY FROM s.created_at)::int - 1),
          (DATE_TRUNC('month', s.next_billing_date + INTERVAL '4 months') - INTERVAL '1 day')::date
        )
      WHEN 'semiannual' THEN
        LEAST(
          DATE_TRUNC('month', s.next_billing_date + INTERVAL '6 months')::date
            + (EXTRACT(DAY FROM s.created_at)::int - 1),
          (DATE_TRUNC('month', s.next_billing_date + INTERVAL '7 months') - INTERVAL '1 day')::date
        )
      WHEN 'annual' THEN
        LEAST(
          DATE_TRUNC('month', s.next_billing_date + INTERVAL '12 months')::date
            + (EXTRACT(DAY FROM s.created_at)::int - 1),
          (DATE_TRUNC('month', s.next_billing_date + INTERVAL '13 months') - INTERVAL '1 day')::date
        )
      WHEN 'custom' THEN
        -- Custom interval uses days, no month-end drift possible
        s.next_billing_date
          + (COALESCE(s.billing_interval_days, 30) || ' days')::interval
      ELSE s.next_billing_date
    END,
    updated_at = NOW()
  WHERE s.auto_renewal   = TRUE
    AND s.status         = 'active'
    AND s.billing_cycle != 'pay_as_you_go'
    AND s.next_billing_date IS NOT NULL
    AND s.next_billing_date <= CURRENT_DATE
    AND (s.last_paid_at IS NULL
         OR s.last_paid_at::date < s.next_billing_date);

  RETURN v_count;
END;
$$;

-- ─── pg_cron schedule ────────────────────────────────────────────────────────
-- Runs every day at 08:00 UTC.
-- Requires pg_cron to be enabled in Supabase (Database → Extensions → pg_cron).
-- If pg_cron is not yet enabled, enable it first and then run the SELECT below manually.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.schedule(
      'auto-pay-subscriptions',
      '0 8 * * *',
      $$SELECT public.auto_register_subscription_payments()$$
    );
  ELSE
    RAISE NOTICE 'pg_cron not enabled — enable it in Database → Extensions, then run: SELECT cron.schedule(''auto-pay-subscriptions'', ''0 8 * * *'', $$SELECT public.auto_register_subscription_payments()$$);';
  END IF;
END;
$$;
